services:
  sommelier:
    image: sommelier-api
    container_name: sommelier-api
    platform: linux/amd64
    build:
      context: .
      dockerfile: api.dockerfile
    ports:
      - 80:80
    working_dir: /sommelier/api/src
    volumes:
      - ../../:/sommelier
    command: uvicorn main:app --reload --host 0.0.0.0 --port 80