services:
  sommelier:
    image: sommelier-jupyterlab
    container_name: sommelier-jupyterlab
    platform: linux/amd64
    build:
      context: .
      dockerfile: jupyterlab.dockerfile
    ports:
      - 9001:9001
    working_dir: /sommelier/jupyterlab/notebooks
    volumes:
      - ../../:/sommelier
    command: jupyter-lab --ip 0.0.0.0 --port 9001 --allow-root --no-browser